### ISSUE TITLE
Throwing "Failed to launch the browser process!" at launch

### ISSUE THREAD

**Issue by zeus1921** [JueK3y/Instagram-automated-commenting#17]
### Specification

Windows 10, 0.8.3

### Steps to reproduce

Start the bot and it simply not comment at all

### Expected Behavior

should post something

### Actual Behavior

checked comment log activity in instagram and it didnt post anything

**Comment by JueK3y-Prv** [comment]
Have you already added comments to the comment file? You can do that by clicking on "Zusätzliche Optionen" and then on "Kommentare bearbeiten".

**Comment by zeus1921** [comment]
im so sorry, i should read the docs.
I found the problem "Failed to launch the browser process! spawn" installed latest node but the problem remains.

**Comment by zeus1921** [comment]
![imagem](https://user-images.githubusercontent.com/28808082/179352302-675476d0-126a-4ee0-a50d-45275c029884.png)

i also think something is wrong with puppeteer?
![imagem](https://user-images.githubusercontent.com/28808082/179352311-521f7052-5fe4-4c80-b4ff-67ab6d08b6dc.png)

**Comment by JueK3y-Prv** [comment]
Okay, try to uninstall "puppeteer" and install "puppeteer-extra" instead, this should fix the error

**Comment by zeus1921** [comment]
nothing. this seems buggy in my end.
![imagem](https://user-images.githubusercontent.com/28808082/179352659-c9d28d20-2fa6-4b11-be5b-23e9a4687a9d.png)
i click here and nothing happens, is that supose to happen?

**Comment by JueK3y-Prv** [comment]
Okay, I will try to recreate your problem. Looks like you found some unfinished things. I'm still finishing all the features for the beta release, so some functions & buttons don't work yet. I will better disable non-functioning stuff for now.

**Comment by JueK3y-Prv** [comment]
I assume you cloned the code, right? Which branch did you use to clone the code? Does IAC work normally when you download the latest version (https://github.com/JueK3y/Instagram-automated-commenting/releases/tag/v0.8.3-alpha)?

**Comment by zeus1921** [comment]
i just installed with the .exe file.
And yes, it was 0.8.3

**Comment by JueK3y-Prv** [comment]
Version 0.8.4-alpha is out now (https://github.com/JueK3y/Instagram-automated-commenting/releases/tag/v0.8.4-alpha). This should fix the starting error
