### ISSUE TITLE
Options to randomise and don't mention duplicates

### ISSUE THREAD

**Issue by zeus1921** [JueK3y/Instagram-automated-commenting#18]
### Related to a problem

- [ ] The feature request is related to a problem.

### Describe the problem

does the bot duplicate mentions?

### The solution you'd like

not comment duplicate users

### Alternatives you've considered

let's say a instagram giveaway has the rule to not duplicate mentions, it would be useful to have a an feature to do that

**Comment by JueK3y-Prv** [comment]
Hi, IAC 2.0 has two commenting modes:

1. _Endless mode_, where all the given comments are repeated until you decide to stop the software 
2. _Only-once mode_, where all comments in your Comments.txt file will be 
 commented once. IAC 2.0 then stops by itself 

=> Choose only-once mode (available in the next update) to prevent your comments from being duplicated
