### ISSUE TITLE
iac won't run 

### ISSUE THREAD

**Issue by KEDTEDAKIAS** [JueK3y/Instagram-automated-commenting#29]
### Specification

windows 11

### Steps to reproduce

when I click iac after downloading out nothing happens

### Expected Behavior

program to run

### Actual Behavior

nothing is runs in the background

**Comment by JueK3y-Prv** [comment]
Hey, did you install the software after downloading it?

**Comment by JueK3y-Prv** [comment]
Hey, thank you for reporting your issue. So you installed IAC correctly and tried starting the software, right? Is there any error message coming up? Is IAC running in the background (You can check this with the Taskmanager)?

**Comment by KEDTEDAKIAS** [comment]
iac is running in the background but nothing pops up

**Comment by JueK3y-Prv** [comment]
I'll take a closer look at the problem in the next few days. Thank you for your feedback.

**Comment by JueK3y-Prv** [comment]
Did you try to de-activate your Anti-Virus Software? This should fix the problem

**Comment by JueK3y-Prv** [comment]
If you have problems with switching off your anti-virus programme, you can also check [IACs Wiki page](https://github.com/JueK3y/Instagram-automated-commenting/wiki/Help). The information there is for an older version, but most of it still applies to IAC 2.0.

**Comment by JueK3y-Prv** [comment]
I will close this issue ticket for now, as it is solved from my point of view. If you still have problems, just comment under the issue :)
